// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyZPvKNDspichcyKZdkj160CMIHsA2bos',
    appId: '1:617244020392:web:3715acc42758ea4d4f3c9d',
    messagingSenderId: '617244020392',
    projectId: 'zubex-ce99d',
    authDomain: 'zubex-ce99d.firebaseapp.com',
    databaseURL: 'https://zubex-ce99d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zubex-ce99d.firebasestorage.app',
    measurementId: 'G-X7LG52XNXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDguzKz7bBDIfRjU0F8Q-xwp5EwhiZCc4k',
    appId: '1:617244020392:android:d79e3d6455945a2a4f3c9d',
    messagingSenderId: '617244020392',
    projectId: 'zubex-ce99d',
    databaseURL: 'https://zubex-ce99d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zubex-ce99d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDePjfsffR7G3z2Pf6ttiwLOpgpLD3EL7g',
    appId: '1:617244020392:ios:2fadc3fb91c830934f3c9d',
    messagingSenderId: '617244020392',
    projectId: 'zubex-ce99d',
    databaseURL: 'https://zubex-ce99d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zubex-ce99d.firebasestorage.app',
    iosBundleId: 'com.example.madrastiPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDePjfsffR7G3z2Pf6ttiwLOpgpLD3EL7g',
    appId: '1:617244020392:ios:2fadc3fb91c830934f3c9d',
    messagingSenderId: '617244020392',
    projectId: 'zubex-ce99d',
    databaseURL: 'https://zubex-ce99d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zubex-ce99d.firebasestorage.app',
    iosBundleId: 'com.example.madrastiPlus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyokhXV5q4coHFHuCNL0w51MYGt3chNes',
    appId: '1:617244020392:web:be0410a0d2c663324f3c9d',
    messagingSenderId: '617244020392',
    projectId: 'zubex-ce99d',
    authDomain: 'zubex-ce99d.firebaseapp.com',
    databaseURL: 'https://zubex-ce99d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zubex-ce99d.firebasestorage.app',
    measurementId: 'G-JBZBKE97TV',
  );
}
